### ISSUE TITLE
is this project still alive? Any alternative you can recommend?

### ISSUE THREAD

**Issue by gr2m** [mmonteleone/jquery.autotype#6]
I've created an issue 2 years ago https://github.com/mmonteleone/jquery.autotype/issues/2

It'd be a bummer to see it die, it's really useful, espcially in combination with PhantomJS/CasperJS headless testing. But I encounter problems, like `{{enter}}` doesn't work form me. Are you still working on it?

**Comment by ghost** [comment]
this project still works for me, didn't realize it hadn't been updated for 5 years
